title: "Time Series Lab release notes"
remote_theme: psrenergy/just-the-docs
logo: assets/images/psr_logo.png

psr_model: "TSL"

toc:
  - title: Current version
    subfolderitems:
      - page: Time Series Lab 2.1
        url: /timeserieslab2.1
  - title: Older versions
    subfolderitems:
      - page: Time Series Lab 2.0
        url: /timeserieslab2.0
      - page: Time Series Lab 1.1
        url: /timeserieslab1.1
      - page: Time Series Lab 1.0
        url: /timeserieslab1.0


#adding zoom in images
zoom_img_enabled: true

#dark/light mode
change_color_enabled: true
color_scheme: "dark"

url: "https://tsl-release-notes.psr-inc.com"

back_to_top: true
back_to_top_text: "Back to top"
footer_content: "Copyright &copy; <script>document.write(new Date().getFullYear())</script> PSR - <a href='https://www.psr-inc.com' target='_blank'>psr-inc.com</a>"
